DROP TABLE IF EXISTS CAU_PARTES;
DROP TABLE IF EXISTS CAU_USUARIOS;
CREATE TABLE CAU_USUARIOS
	(
	USUARIO_ID INTEGER NOT NULL AUTO_INCREMENT ,
	USUARIO VARCHAR(10)  NOT NULL ,
	PASSWORD VARCHAR(10)  NOT NULL ,
	PRIMARY KEY(USUARIO_ID)  );






create table CAU_PARTES
	(
	PARTE_ID INTEGER NOT NULL AUTO_INCREMENT ,
	SERVICIO VARCHAR( 50 ),
	TELEFONO VARCHAR( 50 ),
	AVERIA VARCHAR( 50 ),
	FECHA	DATE,
	PRIMARY KEY(PARTE_ID)
	);
	
INSERT INTO CAU_USUARIOS ( USUARIO, PASSWORD ) VALUES ( 'fernando', 'fernando');


INSERT INTO CAU_PARTES (  SERVICIO, TELEFONO, AVERIA, FECHA ) VALUES (  'CONTABILIDAD', '660444444', 'NO ENCIENDE', '2014-11-10');
